version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 10
